# Generated by Django 3.0.3 on 2020-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'parent__id', 'name'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.Lesson', verbose_name='Родительский урок'),
        ),
    ]
