# Generated by Django 3.0.3 on 2020-03-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', '-level', 'name'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='parent',
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень урока'),
            preserve_default=False,
        ),
    ]
