# Generated by Django 3.0.3 on 2020-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200302_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'level', 'name'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст урока'),
        ),
    ]
