# Generated by Django 3.0.3 on 2020-03-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200302_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['block', 'name'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя блока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to='base.Course', verbose_name='Курс')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.LessonBlock', verbose_name='Родительский блок')),
            ],
            options={
                'verbose_name': 'блок уроков',
                'verbose_name_plural': 'блоки уроков',
                'db_table': 'lesson_blocks',
                'ordering': ['course', 'parent__id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='base.LessonBlock', verbose_name='Блок уроков'),
        ),
    ]
