# Generated by Django 3.0.3 on 2020-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200304_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='task_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст задания урока'),
        ),
        migrations.AddField(
            model_name='lessontest',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
    ]
